# -*- coding: utf-8 -*-
"""Dog Motion Pattern Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M8WLZoFygSg4h2h_u2QIfZc55eT0RqN-

# Dog Motion Pattern Analysis using Sensor Data
"""

import pandas as pd

data_path = "/content/Dog_Data 1_test dataset.csv"
df = pd.read_csv(data_path)

df.head()

df.info()

df = df.drop(columns=["index", "tag_no"], errors="ignore")

df.head()

df.isnull().sum()

"""## no missing values(but im adding forward fill and backward fill)"""

df=df.fillna(method='ffill').fillna(method='bfill')

import numpy as np

df["SMA"] = df[["ax", "ay", "az"]].abs().sum(axis=1)
df[["ax", "ay", "az", "SMA"]].head()

import matplotlib.pyplot as plt

plt.figure(figsize=(12,4))
plt.plot(df["SMA"])
plt.title("SMA over time")
plt.xlabel("Time Index")
plt.ylabel("SMA")
plt.show()

"""## Feature scaling"""

from sklearn.preprocessing import StandardScaler

features = ["ax", "ay", "az", "gx", "gy", "gz", "SMA"]
X = df[features]

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

"""## importing kmeans"""

from sklearn.cluster import KMeans

kmeans = KMeans(n_clusters=3, random_state=20)
df["kmeans_cluster"] = kmeans.fit_predict(X_scaled)

from sklearn.utils import resample
from sklearn.metrics import silhouette_score

X_sample, cluster_sample = resample(
    X_scaled, df["kmeans_cluster"], n_samples=3000, random_state=20
)

silhouette_score(X_sample, cluster_sample)

from sklearn.utils import resample
from sklearn.metrics import silhouette_score

X_sample, cluster_sample = resample(
    X_scaled, df["kmeans_cluster"], n_samples=5000, random_state=42
)

silhouette_score(X_sample, cluster_sample)

"""##PCA visualization"""

from sklearn.decomposition import PCA

pca = PCA(n_components=2)
X_pca = pca.fit_transform(X_scaled)

plt.figure(figsize=(6,6))
plt.scatter(X_pca[:,0], X_pca[:,1], c=df["kmeans_cluster"], s=5)
plt.title("KMeans Clusters -PCA Projection")
plt.xlabel("PCA 1")
plt.ylabel("PCA 2")
plt.show()

df.groupby("kmeans_cluster")["SMA"].describe()

"""##importing DBSCAN"""

from sklearn.cluster import DBSCAN

X_small = X_scaled[:5000]

dbscan = DBSCAN(eps=0.5, min_samples=10)
labels = dbscan.fit_predict(X_small)

pd.Series(labels).value_counts()